# Generated by Django 3.2.5 on 2022-05-21 18:25

from django.db import migrations, models
import manager.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(upload_to=manager.utils.profile_image_path)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
    ]
