# Generated by Django 3.2.5 on 2022-06-04 09:39

from django.db import migrations, models
import django.db.models.deletion
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=manager.utils.training_image_path)),
                ('active', models.BooleanField(default=True)),
                ('face_location', models.TextField()),
                ('face_encoding', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encodings', to='manager.student')),
            ],
        ),
    ]
