# Generated by Django 3.2.5 on 2022-07-28 20:14

from django.db import migrations, models
import manager.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='screen_shot',
            field=models.ImageField(upload_to=manager.utils.utils.screen_shot_image_path),
        ),
    ]
