# Generated by Django 3.2.5 on 2022-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_violation_screen_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('mask', 'Mask'), ('no_mask', 'No Mask'), ('mask_not_in_position', 'Mask not weared correctly')], default='no_mask', max_length=60),
        ),
    ]
