# Generated by Django 3.2.5 on 2022-07-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_violation_violation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='violation_type',
        ),
    ]
